### ISSUE TITLE
Request fixture

### ISSUE THREAD

**Issue by krackxor** [FlyingFathead/whisper-transcriber-telegram-bot#2]
Please support the video format and increase the maximum file size to 4 GB. Thank you.

**Comment by FlyingFathead** [comment]
Receiving video formats is supported if you uncomment them in the `config.ini`, **however, if you're referring to file sizes when sending files directly, the problem is at Telegram's end: Telegram bots cannot receive files over `20 MB` in size.**

There's nothing I can do about it, but if you can put your files into an accessible http(s) location and pass the URL to the bot, `yt-dlp` should be able to fetch it in many cases. It works basically just about all video platforms where the video is available, no matter how big or long in length it is.

Another workaround would be to just run Whisper locally if you have direct access to the file(s), and skip the Whisper bot altogether.

Also, Whisper doesn't really _need_ the video file for the transcript -- you could just dump the video file into audio with i.e. `ffmpeg`:

```
ffmpeg -i input_video.mp4 -vn -ar 44100 -ac 2 -b:a 128k output_audio.mp3
```

And then, if the audio file is still over `20 MB` and needs further segmentation, you could i.e. split it into smaller pieces:

```
ffmpeg -i output_audio.mp3 -f segment -segment_time 1200 -c copy chunks/output_part_%03d.mp3
```

(Or something along those lines, to stay under the 20MB file size limit for bots on Telegram.)

I hope this helps, thank you and have a nice day.

**Comment by krackxor** [comment]
Thanks🙏
