### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by krackxor** [FlyingFathead/whisper-transcriber-telegram-bot#3]
![Screenshot_20241001-223513](https://github.com/user-attachments/assets/d4cc745e-aca4-4ff1-9394-2653a98246a3)

**Comment by FlyingFathead** [comment]
That's an odd bug that I'm working on rn -- try disabling the send-as-messages transcripts from `config.ini`  by setting`sendasmessages = True` to `False` as  a temporary workaround. 

It occasionally happens only with longer files that TG tries to parse into messages. 

Also, please make sure that you've cloned the newest version that's out just today (v0.17). You can check your version with `/about`

**Comment by FlyingFathead** [comment]
I've pushed the latest changes to the main branch that aim to fix the issue with an improved exception catching block -- the issue was in Telegram's message length cap that sometimes overflows when longer messages are chunked into sequences, I've now redone the logic for that. 

**Please pull the latest version (`v0.1701`) using this command:**

```bash
git pull origin main
```

You can also re-clone the repository if that doesn't work for you. 

If you still get the error, please re-open another issue with preferably a copypaste from the backend, and I'll look into it. 

Thanks and have a nice day!

**Comment by krackxor** [comment]
Tanks bro
