### ISSUE TITLE
AMD GPU

### ISSUE THREAD

**Issue by ManuXD32** [FlyingFathead/whisper-transcriber-telegram-bot#6]
Hi, I was wondering if there's a way to make it work with an AMD GPU.

Thank you in advance!!

**Comment by FlyingFathead** [comment]
Hi there!

You could try forking the repo and tinkering around with i.e. [ZLUDA](https://github.com/vosen/ZLUDA) (a drop-in replacement for CUDA on AMD GPU's). There are of course absolutely no guarantees that it will work, given how wonky CUDA itself can be for Nvidia cards.

You can also  run the program in CPU-only mode, the current `turbo` model might not be too bad for that, especially on newer multi-core processors, and if speed isn't a major deal.

I don't think I have any recent-enough AMD cards around here that would enable me to write a ZLUDA stuff or try out the compatibility, so that's sadly something I'm unable to look into myself. However, all the best if you decide to tinker around with ZLUDA, and you can always leave a new issue or even a PR if you do happen to get it working on AMD cards.

Have a nice day, and all the best.

**Comment by ManuXD32** [comment]
Oh okay, thank you so much, gonna try to make it work, I'll make a PR if I get something usable.

Have a nice one you too :)
